var myList={
	
	"smallDogs":{
		"head":"Small Dogs",
		"foot":"1-20lbs",
		"item":[
			
			{"title":"Chihuahua", "description": "The Chihuahua is very spicy. They are active-minded, smart, quick to react, loving, little dogs. They are very tiny, but act as if they're big dogs. Most are very attached to their owners, and can be overly protective. They will need to be taught from an early age that they are not the ones in charge, or they will take over. They tend to have a dominant disposition, but each Chi is different. ", "images": "http://cdn-3.justdogbreeds.com/images/breeds/chihuahua.jpg"},
			{"title":"Italian Greyhound", "description": "The Italian Greyhound is a slender, fine-boned little dog. The head is long and narrow, almost flat on the top with a muzzle that tapers to a point. It has a slight stop. The nose is black or brown, depending on the color of the dog's coat. The teeth meet in a scissors bite. The medium-sized eyes are dark. The small ears fold back along the head, and when the dog is alert they angle to the right. The long neck is arched. The chest is deep and narrow. The front legs are straight. Dewclaws may be removed. The long, low-set tail is thin, tapering to a point. The short, glossy coat comes in all colors, including gray, slate gray, red, fawn, blue, black, white or cream. The dogs can be white with color markings or color with white markings on the chest and feet. A flecked version also exists but is not accepted in all countries. Brindle and black and tan are not accepted into the AKC show ring.", "images": "http://cdn-0.justdogbreeds.com/images/breeds/italian-greyhound.jpg"},
			{"title":"Japanese Chin", "description": "The Japanese Chin dog breed hails from Asia, where he has been prized as a companion for more than a thousand years. He was a popular member of Chinese and Japanese imperial courts, and it was in Japan that his distinctive look was developed. This breed is elegant and dainty, mild-mannered and playful.", "images": "http://cdn-4.justdogbreeds.com/images/breeds/japanese-chin.jpg"}
		]
	},
	
	"largeDogs":{
		"head":"Large Dogs",
		"foot":"+20lbs",
		"item":[
			{"title":"Afghan Hound", "description": "The Afghan Hound is considered an aristocratic sighthound. Tall and slender with a long, narrow, refined head, silky topknot and powerful jaws, the back part of the head and skull are quite prominent. The muzzle is slightly convex and the nose is black. The Afghan has little or no stop, which is the transition area from backskull to muzzle. The teeth should meet in a level or scissors bite. The dark eyes are almond shaped. The ears lie flat to the head. The neck is long and strong. The height at the withers should be almost level and the abdomen well tucked up. The hipbones are quite prominent. The front legs are strong and straight and the feet are large and covered with long hair. The tail has a curl or ring at the tip, but is not carried over the back. The long, rich, silky coat is most often the color of sand with a darker face and ear fringes, though all colors are permitted. White markings, however, are discouraged.", "images": "http://cdn-1.justdogbreeds.com/images/breeds/afghan-hound.jpg"},
			{"title":"Airedale Terrier", "description": "The Airedale Terrier is the largest of the terriers and stands square in appearance. The skull is about the same length as the muzzle, with a very slight stop that is hard to see. The head is long and flat. The nose is black. The teeth should meet in a level, vice-like or scissors bite. The small eyes are dark in color. The V-shaped ears fold slightly to the side of the head and forward. The chest is deep. The topline of the back is level. The front legs are perfectly straight. The tail is set high on the back. The double coat has a hard, dense and wiry outer coat with a soft undercoat. Coat colors include tan and black and tan and grizzle. The head and ears should be tan, with the ears being a slightly darker shade of tan. The legs, thighs, elbows and the under part of the body and chest are also tan, sometimes running into the shoulder. In some lines there is a small white blaze on the chest. The back of the dog, sides and upper parts of the body should be black or dark grizzle in color.", "images": "http://cdn-6.justdogbreeds.com/images/breeds/airedale-terrier.jpg"},
			{"title":"Belgian Malinois", "description": "The Belgian Malinois has a body that is often described as square, as that is the shape it appears to have when the legs and topline are viewed from the side. The chest is deep. The topline is level, sloping slightly at the withers. The overall size of the head is in proportion to the body. The skull is flat with the width and length being of the same distance. The muzzle is somewhat pointed and equal in length to the top of the skull with a moderate stop. The nose is black and so are the tight lips. The teeth meet in a scissors or level bite. The medium sized, almond-shaped eyes are brown. The erect ears are triangular in shape. The tail is strong at the base with the bone reaching to the hock. The feet are cat-like in shape. Dewclaws may be removed. The weather resistant, double-coat is short and straight. The coat color comes in rich fawn to red to mahogany to black, with black tips on the hairs. The mask and ears are black. Underneath the body, the tail and back end are a lighter fawn. The hair around the neck looks like a collar, as it is slightly longer.", "images": "http://cdn-5.justdogbreeds.com/images/breeds/belgian-malinois.jpg"}
		]
	}
	
};
	
exports.json = myList;